### ISSUE TITLE
生成履歴に絵文字を表示する がダウンロード時に無視される

### ISSUE THREAD

**Issue by xtanakax** [emoji-gen/web-main#93]
「生成履歴に絵文字を表示する」をオフにしてもダウンロードをクリックすると履歴に掲載されます

**Comment by pine** [comment]
@xtanakax -san
不具合報告ありがとうございます。確認します。

**Comment by pine** [comment]
@xtanakax -san
対応遅くなり申し訳ありません。こちら修正いたしました。
