### ISSUE TITLE
[Feature Request] seperate color picker for light and dark mode

### ISSUE THREAD

**Issue by roeniss** [emoji-gen/web-main#95]
Hi, first thank you for such a cool webapp!

I want to set foreground and background color differently between light mode and dark mode

For example, I want to make something like below: 

![sample image](https://user-images.githubusercontent.com/26613280/233941626-8710e14f-830d-4034-b299-2b8aead96632.png)

**Comment by pine** [comment]
Hello @roeniss, thank you for your suggestion.

May I ask you to explain for what purpose you would use this function?

**Comment by roeniss** [comment]
Hi @pine! 

As you know, in the presented screenshot, the right image is shown in light mode and the left image is shown in dark mode. I think it is very natural to show white text in dark mode when it is black text in light mode.

Let me show you another example: 
<img width="313" alt="Screenshot 2023-04-26 at 23 38 01 by seonghyeok" src="https://user-images.githubusercontent.com/26613280/234610727-0885a043-93e4-481d-8fac-29a2531e2d04.png">

The above image won't be visible easily in dark mode. If I want to use that dark-brown in light mode, I have no choice and have to use the same color in dark mode.

It is not ideal situation for me. How do you think?

**Comment by pine** [comment]
Hi @roeniss.

This is a preview of a generated emoji.
To see how it looks in each mode, the same image is shown on the left and right.

Your suggestion is to set two different colors, isn't it?
If so, two different images will be generated. How do you plan to use it?

**Comment by roeniss** [comment]
> Your suggestion is to set two different colors, isn't it? 

basically, yes @pine.

before go further, I want to make some consensus with you.

I think, if I use light mode setting in chrome browser, `white background and black text (foreground)` would be very natural and intuitive. Besides, if I changed setting to use dark mode in chrome browser, `black background and white foreground` would be also natural. 

Do you agree with me, or not? 

If you do, it means (I guess) that `emoji-gen` might be responsible to show clearly the text in both light and dark modes. But currently, as you know, we can not choose for each mode. Just one color. You can't make people in both modes see it clearly. Or maybe very specific colors could do.

I'm not sure I deliver my intention clearly so let me know if you don't understand my saying. I'll do my best!

**Comment by roeniss** [comment]
@pine  I might miss some points in your saying. Would you please tell me what your concern is? :D

**Comment by roeniss** [comment]
oh... I see why I couldn't get you. 

<img width="533" alt="Screenshot 2023-05-02 at 00 05 32 by seonghyeok" src="https://user-images.githubusercontent.com/26613280/235473559-6a9fac25-5531-45c0-be57-2e37d053057a.png">

When I see this popup in the slack customization page, I thought that we can upload two image for light mode and dark mode.

Now I know it's impossible in the current custom emoji system. 

Sorry for bothering you so long. I have no doubt that it doesn't make sense to add another color picker.

**Comment by pine** [comment]
@roeniss -san
> Now I know it's impossible in the current custom emoji system.

Thank you for your understanding.

I will close the issue for now.
If you need to the new feature in the future, please reopen this or recreate a new issue. Thank you.
